# Generated by Django 5.2.4 on 2025-07-28 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QrReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iu_app.kiosk')),
            ],
        ),
    ]
