# Generated by Django 5.2.4 on 2025-07-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(choices=[('A', 'Model A'), ('B', 'Model B')], max_length=1)),
                ('description', models.TextField()),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='QrReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiosks', models.ManyToManyField(related_name='qr_readers', to='iu_app.kiosk')),
            ],
        ),
    ]
